name: Run Docker Container Actions

on: workflow_dispatch

#on:
#  pull_request:
#    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: netcore-action
        uses: ./.github/actions/netcore-action

      - name: python-action
        uses: ./.github/actions/cat-facts
        id: cat

      - name: notejs-action
        uses: ./.github/actions/issue-maker
        with:
          repoToken: ${{secrets.GITHUB_TOKEN}}
          catFact: ${{steps.cat.outputs.fact}}
          issueTitle: "--- Lab: GitHub Action with Container : Issue  ${{ github.sha }} ---  "
